name: ArgoCD Application

on:
  workflow_run:
    workflows:
      - "Terraform"
    types:
      - completed

env:
  AWS_REGION: "ap-south-1"
  EKS_CLUSTER_NAME: "my-eks-cluster"

jobs:
  argocd-application:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-22.04

    steps:

      # --------------------------------
      # Checkout
      # --------------------------------

      - name: Checkout Source Code
        uses: actions/checkout@v4


      # --------------------------------
      # AWS Authentication
      # --------------------------------

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_1 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_1 }}
          aws-region: ${{ env.AWS_REGION }}


      # --------------------------------
      # Connect kubectl to EKS
      # --------------------------------

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.EKS_CLUSTER_NAME }}


      # --------------------------------
      # Check EKS
      # --------------------------------

      - name: Check EKS Cluster
        run: |
          kubectl get nodes


      # --------------------------------
      # Create Argo CD Application
      # --------------------------------

      - name: Apply Argo CD Application
        run: |
          kubectl apply -f application.yml


      # --------------------------------
      # Check Argo CD Application
      # --------------------------------

      - name: Check Argo CD Application
        run: |
          kubectl get applications -n argocd
