name: ArgoCD Application

on:
  workflow_run:
    workflows:
      - "Terraform"
    types:
      - completed

env:
  AWS_REGION: "ap-south-1"
  EKS_CLUSTER_NAME: "my-eks-cluster"

jobs:
  argocd-application:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-22.04

    steps:

      # --------------------------------
      # Checkout Source Code
      # --------------------------------

      - name: Checkout Source Code
        uses: actions/checkout@v4


      # --------------------------------
      # AWS Authentication
      # --------------------------------

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_1 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_1 }}
          aws-region: ${{ env.AWS_REGION }}


      # --------------------------------
      # Connect kubectl to EKS
      # --------------------------------

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.EKS_CLUSTER_NAME }}


      # --------------------------------
      # Check EKS
      # --------------------------------

      - name: Check EKS Cluster
        run: |
          echo "Checking EKS cluster..."
          kubectl get nodes --request-timeout=30s
          kubectl cluster-info --request-timeout=30s


      # --------------------------------
      # Check Argo CD
      # --------------------------------

      - name: Check Argo CD
        run: |
          echo "Checking Argo CD namespace..."
          kubectl get namespace argocd --request-timeout=30s

          echo "Checking Argo CD Application CRD..."
          kubectl get crd applications.argoproj.io --request-timeout=30s


      # --------------------------------
      # Apply Argo CD Application
      # --------------------------------

      - name: Apply Argo CD Application
        run: |
          echo "Applying Argo CD Application..."

          timeout 60s kubectl apply \
            --validate=false \
            --request-timeout=30s \
            -f argocd/application.yml

          echo "Argo CD Application applied successfully."


      # --------------------------------
      # Check Argo CD Application
      # --------------------------------

      - name: Check Argo CD Application
        run: |
          echo "Checking Argo CD Application..."

          kubectl get application portfolio \
            -n argocd \
            --request-timeout=30s

          echo "Application status:"
          kubectl get application portfolio \
            -n argocd \
            -o wide \
            --request-timeout=30s
