name: Terraform

on:
  workflow_run:
    workflows:
      - "Portfolio Docker Image"
    types:
      - completed

env:
  AWS_REGION: "ap-south-1"
  EKS_CLUSTER_NAME: "my-eks-cluster"

jobs:
  terraform:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04

    steps:

      # --------------------------------
      # Checkout
      # --------------------------------

      - name: Checkout folder
        uses: actions/checkout@v4


      # --------------------------------
      # AWS Authentication
      # --------------------------------

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_1 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_1 }}
          aws-region: ${{ env.AWS_REGION }}


      # --------------------------------
      # Terraform
      # --------------------------------

      - name: Terraform install
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init
        working-directory: environment/dev

      - name: Terraform plan
        run: terraform plan -out=tfplan
        working-directory: environment/dev

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
        working-directory: environment/dev


      # --------------------------------
      # Connect kubectl to EKS
      # --------------------------------

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Check EKS Cluster
        run: |
          kubectl get nodes


      # --------------------------------
      # Create Argo CD Namespace
      # --------------------------------

      - name: Create Argo CD Namespace
        run: |
          kubectl create namespace argocd \
            --dry-run=client \
            -o yaml | kubectl apply -f -


      # --------------------------------
      # Install Argo CD in EKS
      # --------------------------------

      - name: Install Argo CD
        run: |
          kubectl apply \
            -n argocd \
            --server-side \
            --force-conflicts \
            -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml


      # --------------------------------
      # Wait for Argo CD
      # --------------------------------

      - name: Wait for Argo CD Server
        run: |
          kubectl wait \
            --for=condition=Available \
            deployment/argocd-server \
            -n argocd \
            --timeout=300s


      # --------------------------------
      # Check Argo CD
      # --------------------------------

      - name: Check Argo CD
        run: |
          kubectl get pods -n argocd
          kubectl get svc -n argocd
